version: "2.3"
services:
  redis:
    restart: always
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - "./redisdata:/data"

  worker:
    build: .
    image: yukimochi/activity-relay
    restart: always
    init: true
    working_dir: /Activity-Relay/
    command: worker
    volumes:
      - "./actor.pem:/actor.pem"
      - "./config.yaml:/Activity-Relay/config.yaml"
    depends_on:
      - redis

  spy:
    build: .
    image: yukimochi/activity-relay
    restart: always
    init: true
    working_dir: /Activity-Relay/
    command: spy
    volumes:
      - "./actor.pem:/actor.pem"
      - "./config.yaml:/Activity-Relay/config.yaml"
    depends_on:
      - redis

  server:
    build: .
    image: yukimochi/activity-relay
    restart: always
    init: true
    working_dir: /Activity-Relay/
    command: server
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - "./actor.pem:/actor.pem"
      - "./config.yaml:/Activity-Relay/config.yaml"
      - "./index.html:/Activity-Relay/index.html"
    depends_on:
      - redis
