version: "2.3"
services:
  redis:
    restart: always
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - "./redisdata:/data"

  relay:
    build: .
    image: yukimochi/activity-relay
    restart: always
    init: true
    working_dir: /Activity-Relay/
    command: relay
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - "./config:/Activity-Relay/config"
    depends_on:
      - redis
