name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.x'
      - name: Execute test and upload coverage
        run: |
          go version
          sed --in-place "s/localhost:6379/localhost:$REDIS_PORT/" misc/test/config.yml
          go test -coverprofile=coverage.txt -p 1 . ./api ./command ./deliver ./models
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
